defaults:
  - model: worldgen
  - dataset: 2d3ds
  - _self_

generation_iters: 1
save_path: /mnt/e/3D/experiments/output
splits_path: /mnt/e/3D/experiments/splits
generate: true

tensorboard:
  enabled: true
  log_dir: null
  flush_secs: 30
  log_images: true
  max_images_per_scene: 5

# wandb:
#   enabled: true
#   log_dir: null
#   project: "3d-generation"
#   log_images: true
#   max_images_per_scene: 5

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
