defaults:
  - model: worldgen
  - dataset: ob3d
  - _self_

generation_iters: 2
save_path: /mnt/d/outputs_1
splits_path: /mnt/e/3D/experiments/splits
generate: true
# Удаление .ply файлов после генерации (файлы из dataset.restricted_data_path не удаляются)
remove_generate: true
# Удаление файлов рендеринга камер из сгенерированных .ply файлов (файлы из dataset.restricted_data_path не удаляются)
remove_renders: true

tensorboard:
  enabled: true
  log_dir: null
  flush_secs: 30
  log_images: true
  max_images_per_scene: 5

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
